// <auto-generated />
using System;
using MediAgenda.Infraestructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediAgenda.Infraestructure.Migrations
{
    [DbContext(typeof(MediContext))]
    [Migration("20251214202530_MigracionV8")]
    partial class MigracionV8
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.AnalysisModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Analysis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Prueba para ver tus niveles de globulos rojos y blancos ademas de otros datos, no duele.",
                            Name = "Prueba de sangre"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Un estandar para ver infecciones.",
                            Name = "Analisis de orina"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Imagen para ver fracturas o anomalias a nivel oseo.",
                            Name = "Radiografia"
                        });
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.ApplicationUserModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NameComplete")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7bd25c44-f324-41f7-aae9-43a2f744ef46",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "doctor-concurrency-001",
                            Email = "dr.martinez@mediagenda.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NameComplete = "Carlos Martínez Pérez",
                            NormalizedEmail = "DR.MARTINEZ@MEDIAGENDA.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMYtGJF/SM5CogXcBNxMt7wjuA8/1by854I67fOXznLB9REB7YSpdV6xE4RIs0Q8Eg==",
                            PhoneNumber = "8091234567",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "DOCTOR-SECURITY-STAMP-001",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "1ebe636e-b277-47ea-a2f8-6502cd988476",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "pedro-concurrency-002",
                            Email = "pedro@mediagenda.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NameComplete = "Pedro Alcachofa",
                            NormalizedEmail = "PEDRO@MEDIAGENDA.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMYtGJF/SM5CogXcBNxMt7wjuA8/1by854I67fOXznLB9REB7YSpdV6xE4RIs0Q8Eg==",
                            PhoneNumber = "8093454567",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "PEDRO-SECURITY-STAMP-002",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "12e6b0e1-1eb6-4a4b-8b57-d1a00b31cb46",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "alva-concurrency-003",
                            Email = "alva@mediagenda.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NameComplete = "Alva Alcachofa",
                            NormalizedEmail = "ALVA@MEDIAGENDA.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMYtGJF/SM5CogXcBNxMt7wjuA8/1by854I67fOXznLB9REB7YSpdV6xE4RIs0Q8Eg==",
                            PhoneNumber = "8093543337",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ALVA-SECURITY-STAMP-003",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "12e6b0e1-1eb6-4a4b-8b57-a7d8adf78sdf",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "rufino-concurrency-004",
                            Email = "rufino@mediagenda.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NameComplete = "Rufino Alcachofa",
                            NormalizedEmail = "RUFINO@MEDIAGENDA.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMYtGJF/SM5CogXcBNxMt7wjuA8/1by854I67fOXznLB9REB7YSpdV6xE4RIs0Q8Eg==",
                            PhoneNumber = "8491782495",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "RUFINO-SECURITY-STAMP-004",
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.ClinicModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Clinics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "KM 9 de la Autopista Duarte",
                            Name = "Clinica 9",
                            PhoneNumber = "8095475432"
                        });
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.ConsultationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayAvailableId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("ReasonId")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("Turn")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DayAvailableId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ReasonId");

                    b.ToTable("Consultations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayAvailableId = 1,
                            PatientId = 1,
                            ReasonId = 1,
                            State = 0,
                            Turn = 1
                        });
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.DayAvailableModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("Limit")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("DaysAvailable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClinicId = 1,
                            Date = new DateOnly(2025, 10, 21),
                            EndTime = new TimeOnly(16, 0, 0),
                            Limit = 15,
                            StartTime = new TimeOnly(8, 0, 0)
                        });
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.DoctorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AboutMe")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutMe = "Especialista en cardiologia con 10 años de experiencia.",
                            Specialty = "Cardiologia",
                            UserId = "7bd25c44-f324-41f7-aae9-43a2f744ef46"
                        });
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.InsuranceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Insurances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Humano"
                        });
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.MedicalDocumentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalDocuments");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.MedicineModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Medicines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "An analgesic and antipyretic medication used to treat pain and fever.",
                            Format = "Tablet",
                            IsActive = true,
                            Name = "Paracetamol"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A nonsteroidal anti-inflammatory drug (NSAID) used to reduce inflammation, pain, and fever.",
                            Format = "Capsule",
                            IsActive = true,
                            Name = "Ibuprofen"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A penicillin-type antibiotic used to treat a variety of bacterial infections.",
                            Format = "Tablet",
                            IsActive = true,
                            Name = "Amoxicillin"
                        });
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.NoteConsultationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsultationId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId");

                    b.ToTable("NotesConsultations");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.NotePatientModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("NotesPatients");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.PatientModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Bloodtype")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InsuranceId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("InsuranceId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bloodtype = 6,
                            DateOfBirth = new DateTime(2004, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = 0,
                            Identification = "40214353345",
                            InsuranceId = 1,
                            UserId = "1ebe636e-b277-47ea-a2f8-6502cd988476"
                        },
                        new
                        {
                            Id = 2,
                            Bloodtype = 7,
                            DateOfBirth = new DateTime(2004, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = 1,
                            Identification = "40243453345",
                            InsuranceId = 1,
                            UserId = "12e6b0e1-1eb6-4a4b-8b57-d1a00b31cb46"
                        },
                        new
                        {
                            Id = 3,
                            Bloodtype = 0,
                            DateOfBirth = new DateTime(2000, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = 0,
                            Identification = "40234533343",
                            InsuranceId = 1,
                            UserId = "12e6b0e1-1eb6-4a4b-8b57-a7d8adf78sdf"
                        });
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.PermissionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.PrescriptionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsultationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneralRecomendations")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("LastPrint")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId")
                        .IsUnique();

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.ReasonModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Reasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Available = true,
                            Title = "Consulta"
                        },
                        new
                        {
                            Id = 2,
                            Available = true,
                            Title = "Primera vez"
                        },
                        new
                        {
                            Id = 3,
                            Available = true,
                            Title = "Permiso"
                        },
                        new
                        {
                            Id = 4,
                            Available = true,
                            Title = "Referimiento"
                        },
                        new
                        {
                            Id = 5,
                            Available = true,
                            Title = "Entrega de Estudios"
                        });
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.Relations.HistoryMedicamentsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("EndMedication")
                        .HasColumnType("date");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartMedication")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PatientId");

                    b.ToTable("HistoryMedicaments");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.Relations.PrescriptionAnalysisModel", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int");

                    b.Property<int>("AnalysisId")
                        .HasColumnType("int");

                    b.Property<string>("Recomendations")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PrescriptionId", "AnalysisId");

                    b.HasIndex("AnalysisId");

                    b.ToTable("PrescriptionsAnalysis");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.Relations.PrescriptionMedicineModel", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDosage")
                        .HasColumnType("date");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("StartDosage")
                        .HasColumnType("date");

                    b.HasKey("PrescriptionId", "MedicineId");

                    b.HasIndex("MedicineId");

                    b.ToTable("PrescriptionsMedicines");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.Relations.PrescriptionPermissionModel", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("PrescriptionId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("PrescriptionsPermisions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-role-id",
                            ConcurrencyStamp = "admin-role-stamp-001",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "doctor-role-id",
                            ConcurrencyStamp = "doctor-role-stamp-002",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = "user-role-id",
                            ConcurrencyStamp = "user-role-stamp-003",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "7bd25c44-f324-41f7-aae9-43a2f744ef46",
                            RoleId = "doctor-role-id"
                        },
                        new
                        {
                            UserId = "1ebe636e-b277-47ea-a2f8-6502cd988476",
                            RoleId = "user-role-id"
                        },
                        new
                        {
                            UserId = "12e6b0e1-1eb6-4a4b-8b57-d1a00b31cb46",
                            RoleId = "user-role-id"
                        },
                        new
                        {
                            UserId = "12e6b0e1-1eb6-4a4b-8b57-a7d8adf78sdf",
                            RoleId = "user-role-id"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.ConsultationModel", b =>
                {
                    b.HasOne("MediAgenda.Infraestructure.Models.DayAvailableModel", "DayAvailable")
                        .WithMany("Consultations")
                        .HasForeignKey("DayAvailableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediAgenda.Infraestructure.Models.PatientModel", "Patient")
                        .WithMany("Consultations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediAgenda.Infraestructure.Models.ReasonModel", "Reason")
                        .WithMany("Consultations")
                        .HasForeignKey("ReasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DayAvailable");

                    b.Navigation("Patient");

                    b.Navigation("Reason");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.DayAvailableModel", b =>
                {
                    b.HasOne("MediAgenda.Infraestructure.Models.ClinicModel", "Clinic")
                        .WithMany("DaysAvailable")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.DoctorModel", b =>
                {
                    b.HasOne("MediAgenda.Infraestructure.Models.ApplicationUserModel", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("MediAgenda.Infraestructure.Models.DoctorModel", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.MedicalDocumentModel", b =>
                {
                    b.HasOne("MediAgenda.Infraestructure.Models.PatientModel", "Patient")
                        .WithMany("MedicalDocuments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.NoteConsultationModel", b =>
                {
                    b.HasOne("MediAgenda.Infraestructure.Models.ConsultationModel", "Consultation")
                        .WithMany("Notes")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.NotePatientModel", b =>
                {
                    b.HasOne("MediAgenda.Infraestructure.Models.PatientModel", "Patient")
                        .WithMany("Notes")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.PatientModel", b =>
                {
                    b.HasOne("MediAgenda.Infraestructure.Models.InsuranceModel", "Insurance")
                        .WithMany("Patients")
                        .HasForeignKey("InsuranceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediAgenda.Infraestructure.Models.ApplicationUserModel", "User")
                        .WithOne("Patient")
                        .HasForeignKey("MediAgenda.Infraestructure.Models.PatientModel", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Insurance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.PrescriptionModel", b =>
                {
                    b.HasOne("MediAgenda.Infraestructure.Models.ConsultationModel", "Consultation")
                        .WithOne("Prescription")
                        .HasForeignKey("MediAgenda.Infraestructure.Models.PrescriptionModel", "ConsultationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.Relations.HistoryMedicamentsModel", b =>
                {
                    b.HasOne("MediAgenda.Infraestructure.Models.MedicineModel", "Medicine")
                        .WithMany("HystoryMedicaments")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediAgenda.Infraestructure.Models.PatientModel", "Patient")
                        .WithMany("HystoryMedicaments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.Relations.PrescriptionAnalysisModel", b =>
                {
                    b.HasOne("MediAgenda.Infraestructure.Models.AnalysisModel", "Analysis")
                        .WithMany("PrescriptionAnalyses")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediAgenda.Infraestructure.Models.PrescriptionModel", "Prescription")
                        .WithMany("PrescriptionAnalysis")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Analysis");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.Relations.PrescriptionMedicineModel", b =>
                {
                    b.HasOne("MediAgenda.Infraestructure.Models.MedicineModel", "Medicine")
                        .WithMany("PrescriptionMedicines")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediAgenda.Infraestructure.Models.PrescriptionModel", "Prescription")
                        .WithMany("PrescriptionMedicines")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.Relations.PrescriptionPermissionModel", b =>
                {
                    b.HasOne("MediAgenda.Infraestructure.Models.PermissionModel", "Permission")
                        .WithMany("PrescriptionPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediAgenda.Infraestructure.Models.PrescriptionModel", "Prescription")
                        .WithMany("PrescriptionPermissions")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MediAgenda.Infraestructure.Models.ApplicationUserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MediAgenda.Infraestructure.Models.ApplicationUserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediAgenda.Infraestructure.Models.ApplicationUserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MediAgenda.Infraestructure.Models.ApplicationUserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.AnalysisModel", b =>
                {
                    b.Navigation("PrescriptionAnalyses");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.ApplicationUserModel", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.ClinicModel", b =>
                {
                    b.Navigation("DaysAvailable");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.ConsultationModel", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("Prescription")
                        .IsRequired();
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.DayAvailableModel", b =>
                {
                    b.Navigation("Consultations");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.InsuranceModel", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.MedicineModel", b =>
                {
                    b.Navigation("HystoryMedicaments");

                    b.Navigation("PrescriptionMedicines");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.PatientModel", b =>
                {
                    b.Navigation("Consultations");

                    b.Navigation("HystoryMedicaments");

                    b.Navigation("MedicalDocuments");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.PermissionModel", b =>
                {
                    b.Navigation("PrescriptionPermissions");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.PrescriptionModel", b =>
                {
                    b.Navigation("PrescriptionAnalysis");

                    b.Navigation("PrescriptionMedicines");

                    b.Navigation("PrescriptionPermissions");
                });

            modelBuilder.Entity("MediAgenda.Infraestructure.Models.ReasonModel", b =>
                {
                    b.Navigation("Consultations");
                });
#pragma warning restore 612, 618
        }
    }
}
